import { defineField, defineType } from 'sanity'

export const postType = defineType({
  name: 'post',
  title: 'Article',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string' }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' } }),
    // Category for filtering
    defineField({ 
      name: 'category', 
      title: 'Category', 
      type: 'string',
      options: {
        list: [
          { title: 'Market Insights', value: 'Market Insights' },
          { title: 'Industry News', value: 'Industry News' },
          { title: 'Factory Tips', value: 'Factory Tips' },
          { title: 'Product Guides', value: 'Product Guides' }
        ],
      }
    }),
    // CRITICAL: For storing the raw HTML generated by the AI
    defineField({ name: 'htmlContent', title: 'Raw HTML Content', type: 'text', rows: 20 }),
    // description usually acts as excerpt
    defineField({ name: 'description', title: 'Excerpt / Description', type: 'text', rows: 3 }),
    // CRITICAL: For storing WP numeric IDs (Evolution 301 uses these for updates/media linking)
    defineField({ name: 'wordpressId', title: 'WordPress ID', type: 'string' }),
    // CRITICAL: For storing intercepted RankMath/Yoast SEO data
    defineField({ name: 'seoTitle', title: 'SEO Title', type: 'string' }),
    defineField({ name: 'seoDescription', title: 'SEO Description', type: 'text' }),
    defineField({ name: 'mainImage', title: 'Cover Image', type: 'image' }),
    defineField({ name: 'publishedAt', title: 'Published At', type: 'datetime' })
  ]
})
