import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

import { createClient } from 'next-sanity'

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'hm6skjpo',
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2024-01-01',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN,
})

async function main() {
  // Delete posts with draft-* slugs (auto-generated by Sanity when no proper slug provided)
  const posts = await client.fetch(`*[_type == "post" && defined(slug.current) && slug.current match "draft-*"] { _id, title, "slug": slug.current }`)
  console.log(`Found ${posts.length} draft posts:`)
  posts.forEach((p: any) => console.log(`  - ${p._id}: ${p.title || '(no title)'} (slug: ${p.slug})`))

  if (posts.length > 0) {
    console.log('\nDeleting...')
    const tx = client.transaction()
    for (const post of posts) {
      tx.delete(post._id)
    }
    await tx.commit()
    console.log(`Deleted ${posts.length} posts`)
  } else {
    console.log('No draft posts to delete.')
  }
}

main().catch(console.error)
